language: php

php:
   - 7.0
   - 5.6
   - 5.5
   - 5.4

before_script:
   - composer self-update
   - composer update

script: phpunit --debug --colors --bootstrap vendor/autoload.php tests_phpunit/TestPagarme.php
