language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
before_script:
  - composer install --no-interaction --prefer-dist --dev
  - composer require satooshi/php-coveralls:* --dev
script:
  - vendor/bin/phpunit
  - vendor/bin/behat
after_success:
- php vendor/bin/coveralls -v -c .coveralls.yml
