version: '2'
services:
  php:
    image: php:5.6
    volumes:
      - .:/code
    working_dir: /code
  composer:
    image: pagarme/composer:php5.6
    volumes:
      - .:/code
    working_dir: /code
